### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by nicoleversetwo** [griffithlab/pVACtools#884]
* pvactooIls version: most recent
* Python version: Python 3.9.15
* Operating System: linux/HPC

**Describe the bug**
I'm running into ongoing issues attempting to install pvactools using multiple methods. I have created a conda environment with the latest version of python, and attempt to use pip. I've gone through a lot of the previous user issues and found the suggestions for using a requirements file, as well as attempting to use pip3 for some of the dependencies. Reading through many of the installation issues, it seems this issue with pip/etc is common.

I downloaded a desktop version of docker, but the free versions does not have enough space to run the instance. Our HPC system does not allow Docker, but does have a singurity instance. I'm wondering if it's easiest to use sandbox and copy this over? I've read through some other user issues that seem to have gotten this working, but I just want to make sure I'm using the right docker image for this process, since I don't think I will be able to install pvactools using pip.

**To Reproduce**
(pvacTOOLS) pip install -r /common/yeagern/requirements.txt pvactools

**Log Output**
Collecting pvactools
  Using cached pvactools-3.1.0-py3-none-any.whl (10.0 MB)
Collecting absl-py==1.0.0
  Using cached absl_py-1.0.0-py3-none-any.whl (126 kB)
Requirement already satisfied: appdirs==1.4.4 in /common/yeagern/anaconda_new/envs/pvacTOOLS/lib/python3.9/site-packages (from -r /common/yeagern/requirements.txt (line 2)) (1.4.4)
Collecting astropy==4.1.0
  Using cached astropy-4.1.tar.gz (7.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/common/yeagern/anaconda_new/envs/pvacTOOLS/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/common/yeagern/anaconda_new/envs/pvacTOOLS/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/common/yeagern/anaconda_new/envs/pvacTOOLS/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-yawx0vub/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-yawx0vub/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-yawx0vub/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 70, in <module>
        File "/tmp/pip-build-env-yawx0vub/overlay/lib/python3.9/site-packages/extension_helpers/_setup_helpers.py", line 67, in get_extensions
          ext_modules.extend(setuppkg.get_extensions())
        File "./astropy/modeling/setup_package.py", line 59, in get_extensions
          from jinja2 import Environment, FileSystemLoader
        File "/tmp/pip-build-env-yawx0vub/overlay/lib/python3.9/site-packages/jinja2/__init__.py", line 33, in <module>
          from jinja2.environment import Environment, Template
        File "/tmp/pip-build-env-yawx0vub/overlay/lib/python3.9/site-packages/jinja2/environment.py", line 15, in <module>
          from jinja2 import nodes
        File "/tmp/pip-build-env-yawx0vub/overlay/lib/python3.9/site-packages/jinja2/nodes.py", line 19, in <module>
          from jinja2.utils import Markup
        File "/tmp/pip-build-env-yawx0vub/overlay/lib/python3.9/site-packages/jinja2/utils.py", line 642, in <module>
          from markupsafe import Markup, escape, soft_unicode
      ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/tmp/pip-build-env-yawx0vub/overlay/lib/python3.9/site-packages/markupsafe/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by susannasiebert** [comment]
Hi @nicoleversetwo,

I'm sorry you're running into installation issues with pVACtools. It looks like the error is related to markupsafe:
```ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/tmp/pip-build-env-yawx0vub/overlay/lib/python3.9/site-packages/markupsafe/init.py)  ```
You might be able to find more information googling for that issues specifically. It might be that the version of markupsafe in our requirements file is outdated/not compatible with python 3.9.

I think you might also want to try with an older version of python (3.8 or below). We are working on 3.9 and up support but that won't release until pVACtools version 4.0.

In regards to docker, we have a few different variants of our docker container. Please see here for details: https://pvactools.readthedocs.io/en/latest/pvacseq/getting_started.html#running-pvacseq-using-docker. `latest-xs` only contains pVACtools by itself so that will be the smallest. `latest` will have IEDB and BLAST and is very large as a result. If you aren't planning on using the reference genome feature, I'd recommend going with the `latest-slim` docker container which will give you pVACtools + IEDB.

Best,
Susanna

**Comment by nicoleversetwo** [comment]
Thank you so much for your very prompt and clear response! Downgrading to neither python 3.7 or 3.8 would work, so I ended up using the latest-slim version for docker and was able to get it to load successfully! I'll get going now with our vcfs.  Thank you so much for being so helpful!!
